# Generated by Django 5.2.16 on 2026-08-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_defensedraft'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at']},
        ),
    ]
