# Generated by Django 5.2.17 on 2026-09-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_document_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='legal_sources/%Y/%m/%d/')),
                ('original_name', models.CharField(max_length=255)),
                ('raw_text', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('status', models.CharField(default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='defensedraft',
            name='source_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
