# Generated by Django 5.2.17 on 2026-09-12 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_legalsource_defensedraft_source_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='defensedraft',
            name='attachment_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='CaseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cases.case')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_attachment', to='cases.document')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
